/// Composite pass 5 — Bloom Application + HDR Tonemapping (Lottes 2016)
/// Reads bloom atlas from colortex3 (generated by composite4), applies bloom,
/// then converts HDR scene color (colortex0, R16F) to LDR for final output.
/// Reference: CR composite5.glsl
///
/// Pipeline: composite4 (bloom gen) -> composite5 (bloom apply + tonemap) -> final
/// Output: colortex0 (tonemapped LDR)
#include "../@engine/core/core.hlsl"
#include "../lib/common.hlsl"
#include "../include/settings.hlsl"
#include "../lib/bloom.hlsl"
#include "../lib/tonemap.hlsl"

//============================================================================//
// Main
//============================================================================//

struct PSOutput
{
    float4 color0 : SV_Target0; // colortex0 (tonemapped LDR)
};

/* RENDERTARGETS: 0 */

PSOutput main(PSInput input)
{
    PSOutput output;

    // Read HDR scene color
    float3 hdrColor = colortex0.SampleLevel(sampler0, input.TexCoord, 0).rgb;

    // Apply bloom before tonemap (CR composite5.glsl:161-195)
#if BLOOM_ENABLED == 1
    DoBloom(hdrColor, input.TexCoord);
#endif

    // Apply Lottes tonemap: HDR -> LDR
    float3 ldrColor = LottesTonemap(hdrColor);

    // Apply color saturation/vibrance (CR DoBSLColorSaturation)
    ldrColor = ApplyColorSaturation(ldrColor);

    output.color0 = float4(ldrColor, 1.0);
    return output;
}
