/**
 * @file ImguiSettingCloud.cpp
 * @brief Static ImGui interface for CloudRenderPass debugging - Implementation
 * @date 2025-11-26
 *
 * Implementation Notes:
 * - Uses ImGui::CollapsingHeader for collapsible section
 * - ImGui::SliderFloat for float parameter adjustment (cloud speed, opacity)
 * - ImGui::Checkbox for boolean toggle (Fancy/Fast mode)
 * - ImGui::Text for read-only parameter display (vertex count)
 *
 * Reference:
 * - imgui_demo.cpp:434 (CollapsingHeader example)
 * - imgui_demo.cpp:1089 (Checkbox example)
 * - imgui_demo.cpp:1156 (SliderFloat example)
 */

#include "ImguiSettingCloud.hpp"
#include "CloudRenderPass.hpp"
#include "ThirdParty/imgui/imgui.h"

/**
 * @brief Show - Render cloud rendering debug UI
 *
 * UI Flow:
 * 1. Check cloudPass validity
 * 2. Render CollapsingHeader "Cloud Rendering"
 * 3. Display cloud speed slider (0.0 - 5.0)
 * 4. Display cloud opacity slider (0.0 - 1.0)
 * 5. Display Fancy/Fast mode checkbox
 * 6. Display current vertex count (read-only)
 * 7. Provide reset button to restore defaults
 */
void ImguiSettingCloud::Show(CloudRenderPass* cloudPass)
{
    // [STEP 1] Validate CloudRenderPass pointer
    if (!cloudPass)
    {
        ImGui::TextColored(ImVec4(1.0f, 0.0f, 0.0f, 1.0f), "[ERROR] CloudRenderPass is null");
        return;
    }

    // [STEP 2] CollapsingHeader: Collapsible section for cloud rendering parameters
    // Returns true if expanded, false if collapsed
    if (ImGui::CollapsingHeader("Cloud Rendering"))
    {
        // Indent content for better visual hierarchy
        ImGui::Indent();

        // ==================== Cloud Speed Adjustment ====================

        float cloudSpeed = cloudPass->GetCloudSpeed();
        if (ImGui::SliderFloat("Cloud Speed", &cloudSpeed, 0.0f, 2.0f, "%.2f"))
        {
            cloudPass->SetCloudSpeed(cloudSpeed);
        }

        // Help text for cloud speed
        if (ImGui::IsItemHovered())
        {
            ImGui::SetTooltip("Controls cloud animation speed (default: 1.0)");
        }

        // ==================== Cloud Opacity Adjustment ====================

        float cloudOpacity = cloudPass->GetCloudOpacity();
        if (ImGui::SliderFloat("Cloud Opacity", &cloudOpacity, 0.0f, 1.0f, "%.2f"))
        {
            cloudPass->SetCloudOpacity(cloudOpacity);
        }

        // Help text for cloud opacity
        if (ImGui::IsItemHovered())
        {
            ImGui::SetTooltip("Controls cloud transparency (0.0 = transparent, 1.0 = opaque, default: 0.8)");
        }

        ImGui::Separator();

        // ==================== Fancy/Fast Mode Toggle ====================

        ImGui::Text("Rendering Mode:");
        ImGui::Spacing();

        bool fancyMode = cloudPass->IsFancyMode();
        if (ImGui::Checkbox("Fancy Mode", &fancyMode))
        {
            cloudPass->SetFancyMode(fancyMode);
        }

        // Help text for fancy mode
        if (ImGui::IsItemHovered())
        {
            ImGui::SetTooltip(
                "Fast Mode: 6144 vertices (2 triangles per cell, flat clouds)\n"
                "Fancy Mode: 24576 vertices (8 triangles per cell, volumetric clouds)"
            );
        }

        // Display current mode info
        ImGui::SameLine();
        if (fancyMode)
        {
            ImGui::TextColored(ImVec4(0.0f, 1.0f, 0.0f, 1.0f), "(Volumetric)");
        }
        else
        {
            ImGui::TextColored(ImVec4(0.5f, 0.5f, 0.5f, 1.0f), "(Flat)");
        }

        ImGui::Separator();

        // ==================== Read-Only Info Display ====================

        ImGui::Text("Cloud Mesh Info:");
        ImGui::Spacing();

        // Vertex count (read-only)
        int vertexCount = fancyMode ? 24576 : 6144;
        ImGui::BulletText("Vertex Count: %d", vertexCount);

        // Cell count (read-only)
        ImGui::BulletText("Grid Size: 32x32 cells");

        // Cloud height (read-only)
        if (fancyMode)
        {
            ImGui::BulletText("Cloud Height: Z=192-196 (4 blocks thick)");
        }
        else
        {
            ImGui::BulletText("Cloud Height: Z=192 (single layer)");
        }

        // Help text
        if (ImGui::IsItemHovered())
        {
            ImGui::SetTooltip("Cloud mesh is generated by CloudGeometryBuilder");
        }

        // ==================== Reset to Defaults ====================

        ImGui::Separator();

        if (ImGui::Button("Reset to Defaults"))
        {
            cloudPass->SetCloudSpeed(1.0f); // Default speed
            cloudPass->SetCloudOpacity(0.8f); // Default opacity
            cloudPass->SetFancyMode(false); // Default to Fast mode
        }

        // Help text for reset button
        if (ImGui::IsItemHovered())
        {
            ImGui::SetTooltip("Reset all cloud parameters to Minecraft vanilla defaults");
        }

        ImGui::Unindent();
    }
}
